In [59]:
import pandas as pd
import numpy as np

In [60]:
df=pd.read_csv('Dirty data.csv')
df

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,7,NaN,NaN,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,NaN,NaN,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,NaN,NaN,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,NaN,NaN,"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,NaN,14[17],"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,NaN,NaN,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,1[20],NaN,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]
14,15,2[c],NaN,"$194,000,000","$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,NaN,NaN,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,NaN,NaN,"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,NaN,NaN,"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,NaN,NaN,"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,NaN,NaN,"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

# Missing Check

In [61]:
print(f"Missing\n{df.isnull().sum()}")
print(f"\n%Missing\n{df.isna().mean()*100}")

Missing
Rank                                 0
Peak                                11
All Time Peak                       14
Actual gross                         0
Adjusted gross (in 2022 dollars)     0
Artist                               0
Tour title                           0
Year(s)                              0
Shows                                0
Average gross                        0
Ref.                                 0
dtype: int64

%Missing
Rank                                 0.0
Peak                                55.0
All Time Peak                       70.0
Actual gross                         0.0
Adjusted gross (in 2022 dollars)     0.0
Artist                               0.0
Tour title                           0.0
Year(s)                              0.0
Shows                                0.0
Average gross                        0.0
Ref.                                 0.0
dtype: float64

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Rank                              20 non-null     int64
 1   Peak                              9 non-null      object
 2   All Time Peak                     6 non-null      object
 3   Actual gross                      20 non-null     object
 4   Adjusted gross (in 2022 dollars)  20 non-null     object
 5   Artist                            20 non-null     object
 6   Tour title                        20 non-null     object
 7   Year(s)                           20 non-null     object
 8   Shows                             20 non-null     int64
 9   Average gross                     20 non-null     object
 10  Ref.                              20 non-null     object
dtypes: int64(2), object(9)
memory usage: 1.8+ KB

In [63]:
df.sample(3)

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
10,11,NaN,NaN,"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]

In [64]:
df = df.dropna(axis=1)
df = df.drop('Ref.',axis=1)
df

,Rank,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross
0,1,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571"
1,2,"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571"
2,3,"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294"
3,4,"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795"
4,5,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173"
5,6,"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709"
6,7,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405"
7,7,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927"
8,9,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215"
9,10,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882"
10,11,"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606"
11,12,"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227"
12,13,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993"
13,14,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385"
14,15,"$194,000,000","$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333"
15,16,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775"
16,17,"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694"
17,18,"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732"
18,19,"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950"
19,20,"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186"

# Duplicates Check

In [65]:
df.duplicated().sum()

np.int64(0)

# Dtypes Check

In [66]:
df.dtypes

Rank                                 int64
Actual gross                        object
Adjusted gross (in 2022 dollars)    object
Artist                              object
Tour title                          object
Year(s)                             object
Shows                                int64
Average gross                       object
dtype: object

In [67]:
list(df.columns)

['Rank',
 'Actual\xa0gross',
 'Adjusted\xa0gross (in 2022 dollars)',
 'Artist',
 'Tour title',
 'Year(s)',
 'Shows',
 'Average gross']

In [68]:
df.columns = df.columns.str.replace('\xa0', ' ').str.strip()
list(df.columns)

['Rank',
 'Actual gross',
 'Adjusted gross (in 2022 dollars)',
 'Artist',
 'Tour title',
 'Year(s)',
 'Shows',
 'Average gross']

## Clean The Numerical Data

In [69]:
# Remove special Character and Change dtype To Float

In [70]:
df['Actual gross']=(
    df['Actual gross']
    .astype(str)
    .str.replace(r'[^0-9.]','',regex=True)
    .astype(float)
)

In [71]:
df['Adjusted gross (in 2022 dollars)']=(
    df['Adjusted gross (in 2022 dollars)']
    .astype(str)   
    .str.replace(r'[^0-9.]','',regex=True)
    .astype(float)
    
)

In [72]:
df['Average gross']=(
    df['Average gross']
    .astype(str)   
    .str.replace(r'[^0-9.]','',regex=True)
    .astype(float)
)

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Rank                              20 non-null     int64
 1   Actual gross                      20 non-null     float64
 2   Adjusted gross (in 2022 dollars)  20 non-null     float64
 3   Artist                            20 non-null     object
 4   Tour title                        20 non-null     object
 5   Year(s)                           20 non-null     object
 6   Shows                             20 non-null     int64
 7   Average gross                     20 non-null     float64
dtypes: float64(3), int64(2), object(3)
memory usage: 1.4+ KB

In [74]:
df.head()

,Rank,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross
0,1,780000000.0,780000000.0,Taylor Swift,The Eras Tour †,2023–2024,56,13928571.0
1,2,579800000.0,579800000.0,Beyoncé,Renaissance World Tour,2023,56,10353571.0
2,3,411000000.0,560622615.0,Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,4835294.0
3,4,397300000.0,454751555.0,Pink,Beautiful Trauma World Tour,2018–2019,156,2546795.0
4,5,345675146.0,402844849.0,Taylor Swift,Reputation Stadium Tour,2018,53,6522173.0

## Clean The Catagorical Data

### Unique Check

In [75]:
df.Artist.unique()

array(['Taylor Swift', 'Beyoncé', 'Madonna', 'Pink', 'Celine Dion',
       'Lady Gaga', 'Katy Perry', 'Cher', 'Adele'], dtype=object)

In [76]:
df['Tour title'].unique()

array(['The Eras Tour †', 'Renaissance World Tour',
       'Sticky & Sweet Tour ‡[4][a]', 'Beautiful Trauma World Tour',
       'Reputation Stadium Tour', 'The MDNA Tour',
       'Taking Chances World Tour', 'Summer Carnival †',
       'The Formation World Tour', 'The 1989 World Tour',
       'The Mrs. Carter Show World Tour', 'The Monster Ball Tour *',
       'Prismatic World Tour', 'Living Proof: The Farewell Tour ‡[21][a]',
       'Confessions Tour', 'The Truth About Love Tour',
       'Born This Way Ball', 'Rebel Heart Tour', 'Adele Live 2016',
       'The Red Tour'], dtype=object)

In [77]:
df['Tour title'] = (
    df['Tour title']
    .astype(str)
    .str.replace(r'[^a-zA-Z\s&]', '', regex=True)  # keep letters, space, & symbol
    .str.strip()
)

In [78]:
df

,Rank,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross
0,1,780000000.0,780000000.0,Taylor Swift,The Eras Tour,2023–2024,56,13928571.0
1,2,579800000.0,579800000.0,Beyoncé,Renaissance World Tour,2023,56,10353571.0
2,3,411000000.0,560622615.0,Madonna,Sticky & Sweet Tour a,2008–2009,85,4835294.0
3,4,397300000.0,454751555.0,Pink,Beautiful Trauma World Tour,2018–2019,156,2546795.0
4,5,345675146.0,402844849.0,Taylor Swift,Reputation Stadium Tour,2018,53,6522173.0
5,6,305158363.0,388978496.0,Madonna,The MDNA Tour,2012,88,3467709.0
6,7,280000000.0,381932682.0,Celine Dion,Taking Chances World Tour,2008–2009,131,2137405.0
7,7,257600000.0,257600000.0,Pink,Summer Carnival,2023–2024,41,6282927.0
8,9,256084556.0,312258401.0,Beyoncé,The Formation World Tour,2016,49,5226215.0
9,10,250400000.0,309141878.0,Taylor Swift,The World Tour,2015,85,2945882.0
10,11,229100000.0,283202896.0,Beyoncé,The Mrs Carter Show World Tour,2013–2014,132,1735606.0
11,12,227400000.0,295301479.0,Lady Gaga,The Monster Ball Tour,2009–2011,203,1118227.0
12,13,204000000.0,251856802.0,Katy Perry,Prismatic World Tour,2014–2015,151,1350993.0
13,14,200000000.0,299676265.0,Cher,Living Proof The Farewell Tour a,2002–2005,325,615385.0
14,15,194000000.0,281617035.0,Madonna,Confessions Tour,2006,60,3233333.0
15,16,184000000.0,227452347.0,Pink,The Truth About Love Tour,2013–2014,142,1295775.0
16,17,170000000.0,213568571.0,Lady Gaga,Born This Way Ball,2012–2013,98,1734694.0
17,18,169800000.0,207046755.0,Madonna,Rebel Heart Tour,2015–2016,82,2070732.0
18,19,167700000.0,204486106.0,Adele,Adele Live,2016–2017,121,1385950.0
19,20,150000000.0,185423109.0,Taylor Swift,The Red Tour,2013–2014,86,1744186.0

In [79]:
df.to_csv('cleaned_data.csv', index=False)